title: Rohit Menon
logo: /Blog_Images/Rohit.png
email: rmenon12@asu.edu
description: Portolio Website

# Social Profiles
github_username: RohitMenon120192
linkedin_username: rohit-menon 


#show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0    #hacker@v0.2.0 #minimal@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal  ## for minimal theme
